### PR TITLE
Fix fieldname access imosTimeSeriesSpikeQC.m

### PR DESCRIPTION
**Pull request by sspagnol**
Testing for sample_data.FIELDNAME but accessing sample_data.meta.FIELDNAME

### CODE REVIEW

**Comment by ocehugo** [comment]
@sspagnol , is this blocking anything important apart from netcdf?

**Comment by sspagnol** [comment]
For me imosTimeSeriesSpikeQC.m was run when it was in the list of QC data routines, then matlab would throw error and so wouldn't get to the spike window (the one with list of variable and preview button). Dont' know about netcdf stuff. And only tested on a dataset the Vinnie was having trouble with.

**Comment by ocehugo** [comment]
Thanks. Just reproduced.

Lack of automated tests with real files on that one. damn, just minted a release...will need to do another and reverse the check here.

**Comment by ocehugo** [comment]
fixed in #682

**Pull request closed without merging**
