### PR TITLE
fix geomag max_path issue #252

### PR DESCRIPTION
**Pull request by petejan**
fix C source (added in change also) and re-compile for windows and linux

### CODE REVIEW

**Comment by ggalibert** [comment]
Would be nice to have a first commit that includes the original C source and a second one that includes your changes and the new binaries.

**Comment by ggalibert** [comment]
Also, update the relevant matlab script that checks for length of path not to exceed 92 char.

**Comment by ggalibert** [comment]
Please make sure the windows binary has been compiled for win32.

**Comment by ggalibert** [comment]
I'd like to merge this PR before this one https://github.com/aodn/imos-toolbox/pull/286 since the later involves renaming binaries.

**Comment by petejan** [comment]
Yes the windows binaries are for win32
```
C:\Users\jan079\Documents\GitHub\imos-toolbox>objdump -h Geomag\windows\geomag70.exe

Geomag\windows\geomag70.exe:     file format pei-i386
```

**Comment by ggalibert** [comment]
@petejan could you please include the binary for macosx?

**Comment by ggalibert** [comment]
Redundant with clean PR https://github.com/aodn/imos-toolbox/pull/290. Now closing this one.

**Pull request closed without merging**
