### PR TITLE
Sspagnol wqm missingvar, closes #557

### LINKED ISSUE #557: Handle case of WQM which didn't record one of it's primary variables
See PR https://github.com/aodn/imos-toolbox/pull/555 .

@sspagnol can you please upload a zip file of an example of this misbehaved instrument file?

### PR DESCRIPTION
**Pull request by ocehugo**
These are the fixes done on top of PR #555. I had to implement some extras.

I had to refactor since the scope was a bit messy. I think I left the code in better shape.

The PR can generate the structures for all files within the test folder and runTests.m got a pass.

### CODE REVIEW

**Comment by ocehugo** [comment]
@sspagnol

**Comment by ocehugo** [comment]
argh, those binary files + build stuff were not supposed to be there. I mixed match when changing branches.

**Comment by ocehugo** [comment]
@ggalibert ,
cleaned up

**Comment by ocehugo** [comment]
PS: I did a squash of three commits because that is the right thing to do - you want a clean log on the repo, not a log with every hunk committed.

Unfortunately, the diffs are big because the file is messy. windows formatting, leading white spaces, no consistent indentation, large scope. I use auto-lint so a lot of noise was generated. There still some indentation problems though

**Comment by ggalibert** [comment]
> PS: I did a squash of three commits because that is the right thing to do - you want a clean log on the repo, not a log with every hunk committed.

Ok but for reviewing it is a lot harder!!! You could squash after review and before merging.

**Comment by ggalibert** [comment]
For discussion: In the past I used to only merge to master when I was doing a release, so merging a whole bunch of commits + updated binaries at once. The reason was some users would checkout master at any time of dev and use the code to process their data instead of the 2.5 official branch. The actual version of the toolbox used would then be lost.

**Pull request merged**
